---
driver:
  name: vagrant

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 1
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  additional_copy_path:
    - extra_modules
    - filter_plugins
  ansible_vault_password_file: <%= File.expand_path(ENV['ANSIBLE_VAULT_PASSWORD_FILE'] || '') %>

platforms:
  - name: openbsd-6.0-amd64
    driver:
      box: mitsuruy/ansible-openbsd-6.0-amd64
      box_check_update: false
    driver_config:
      ssh:
        shell: '/bin/sh'
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/local/bin/python'

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: test/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I test/serverspec test/serverspec/default_spec.rb
